feature : get cafeLocation from user pos
Fran-Fe/franfe-back pull request #13
Opened 2023-07-23 17:28 UTC by archun39

# AS IS
* 사용자의 위치 및 원하는 위치를 기반으로 근처 카페들의 정보를 가져올 필요가 있었음
*

# TO BE
* 해냄
* DB의 정보가 없어서 저장 후 수정할 예정

# COMPLETED TEST
- DB 연동 테스트 및 객체화 완료

# REFERENCE
*

2023-07-23 22:55 UTC, roganOhDev commented
컨플릭 해결해주세용~

2023-07-23 22:57 UTC, mumat0103 approved these changes
👍

2023-07-23 23:07 UTC, roganOhDev requested changes

2023-07-23 23:07 UTC, roganOhDev commented on src/domain/getCafeLocations/getCafeLocation.js
> +export function findByLatAndLng(userLng, userLat, distance) {
lat, lng 에 의해 찾는건 아니자나요 다른 함수 이름은 없을까요?

2023-07-23 23:07 UTC, roganOhDev commented on src/domain/getCafeLocations/getCafeLocation.js
> +export const CafeInfo = sequelize.define('cafes', {
이거에 대한 migration script를 migrations 에 만들어주세요. migrations/real_queries 에도 리얼 쿼리로 부탁해요~

2023-07-23 23:07 UTC, roganOhDev commented on src/domain/getCafeLocations/getCafeLocation.js
> +});
test/db/drop_tables.sql 에도 테이블 드랍 쿼리 작성해주세요~

2023-07-23 23:07 UTC, roganOhDev commented on src/routes/forFront/getCafeLocationsRoutes.js
> +router.get('/cafeLocation',(req,res) => {
이렇게 하면 트렌젝션 서비스의 함수가 async 라서 에러 핸들링이 안돼요. 한번 cafeRoutes.js 보고 바꿔봐주세용~

2023-07-23 23:07 UTC, roganOhDev commented on src/routes/forFront/getCafeLocationsRoutes.js
> +  res.json(response);
혹시 테스트는 어디 있나요?

2023-07-23 23:07 UTC, roganOhDev commented on src/routes/forFront/getCafeLocationsRoutes.js
> +
역시 cafesRoutes.js 보고 한번 스웨거 주석 만들어봐 주세요

2023-07-25 19:36 UTC, archun39 commented on src/domain/getCafeLocations/getCafeLocation.js
> +export function findByLatAndLng(userLng, userLat, distance) {
findByPosition 으로 바꾸겠습니다

2023-07-25 20:15 UTC, archun39 commented on src/routes/forFront/getCafeLocationsRoutes.js
> +  res.json(response);
만들어 보겠습니다.

2023-07-26 23:31 UTC, closed without merging