Feature/get cafe locations
Fran-Fe/franfe-back pull request #19
Opened 2023-07-26 23:33 UTC by archun39

# AS IS
* 사용자 위치기반 카페 정보 가져오기

# TO BE
* PR 적용

# COMPLETED TEST

# REFERENCE
*

2023-07-26 23:52 UTC, roganOhDev requested changes

2023-07-26 23:52 UTC, roganOhDev commented on test/assertionFactory.js
> +  expect(res.body).to.have.property('uuid');
이거 반환이 리스트라서 body 에는 이런거 없고 리스트가 있을거에요. 아마 제가 이해 했다면 body[0] 이렇게 가져와야 될껄요?
아니면 혹시 테스트 돌려봤을 때 성공했어요?

2023-07-26 23:52 UTC, roganOhDev commented on src/routes/forFront/getCafeLocationsRoutes.js
> +router.get('/cafeLocation',async (req,res) => {
네 주석에 있는 것처럼 수정해주세욤

2023-07-27 00:17 UTC, archun39 commented on test/assertionFactory.js
> +  expect(res.body).to.have.property('uuid');
DB에 위치 경도가 없어서 테스트를 안해봤습니다. 더미 DB로 해볼까요?

2023-07-27 00:17 UTC, archun39 commented on src/routes/forFront/getCafeLocationsRoutes.js
> +router.get('/cafeLocation',async (req,res) => {
어이고 쏘리

2023-07-28 18:55 UTC, roganOhDev commented on test/assertionFactory.js
> +  expect(res.body).to.have.property('uuid');
넹 한번 고고

2023-08-02 18:31 UTC, closed without merging